<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>

<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>

    <div class="owl-button-top above-padding below-padding block widget block-products-list <?php /* @escapeNotVerified */ echo $mode; ?>">
        <?php if ($title): ?>
            <div class="page-title-main">
                <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
            <div class="products-<?php /* @escapeNotVerified */ echo $mode; ?> <?php /* @escapeNotVerified */ echo $mode; ?>">
                <div class="slider-outer">
                    <ol style="margin-bottom: 0;" class="product-widget-slider products list items product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                        <?php $iterator = 1; ?>

                        <?php foreach ($items as $_item): ?>
                            <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="product-slider product-item">' : '</li><li class="product-slider product-item">' ?>
                            
                            <div class="product-item-info container card">
                                <div class="product-img-main">
                                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product-item-photo">
                                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                                    </a>
                                </div>
                                <div class="row d-flex align-items-center">
                                    <div class="col-sm-10 col-md-8 col-lg-9">
                                        <h4 class="font-weight-bold"><?php echo $block->escapeHtml($_item->getName()) ?></h4>
                                    </div>
                                    <div class="col-sm-2 col-md-4 col-lg-3">
                                        <?php
                                            $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <a href="#" data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'><i class="fa fa-cart-plus"></i></a>
                                    </div>
                                </div>
                                <div class="product-item-details">
                                    <?php
                                        echo $block->getProductPriceHtml($_item, $type);
                                    ?>
                                    <?php if ($templateType): ?>
                                        <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                                    <?php endif; ?>
                                    <?php if ($showWishlist || $showCompare || $showCart): ?>
                                        <div class="product-item-inner">
                                            <div class="product-item-actions">
                                                <?php if ($showCart): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_item->isSaleable()): ?>
                                                            <div class="row mt-1">
                                                                <div class="col-lg-12">
                                                                    <!-- Button trigger modal -->
                                                                    <button type="button" class="t-btn t-btn-primary center btn-lg" data-toggle="modal" data-target="#edit" data-img="<?php echo $_item->getData('image'); ?>" data-name="<?php echo $block->escapeHtml($_item->getName()) ?>" data-description="">
                                                                        Vista Rápida
                                                                    </button>
                                                                </div>
                                                            </div>
                                                        <?php else: ?>
                                                            <?php if ($_item->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php echo($iterator == count($items) + 1) ? '</li>' : '' ?>
                        <?php endforeach ?>
                        
                    </ol>
                </div>
            </div>
            <?php echo $block->getPagerHtml() ?>
        </div>
    </div>

 

    <!-- Modal -->
    <div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <input type="text" name="name" class="whithoutBorder h4" id="name">
                    <img id="img"/>
                    <input type="text" name="description" class="whithoutBorder" id="description">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript" xml="space">
        require(['jquery', 'pixtronowlcarousel'], function() {
            jQuery(document).ready(function() {
                jQuery(".product-widget-slider").owlCarousel({
                    items: 5,
                    itemsDesktop: [1198, 5],
                    itemsDesktopSmall: [1023, 4],
                    itemsTablet: [768, 3],
                    itemsTabletSmall: [767, 3],
                    itemsMobile: [479, 2],
                    pagination: false,
                    navigationText: ["<div class='left-arrow'><i class='fa fa-angle-left'></i></div>", "<div class='right-arrow'><i class='fa fa-angle-right'></div>"],
                    navigation: true,
                });
                jQuery('.product-widget-slider .product-slider').show();
                jQuery('#edit').on('show.bs.modal', function (event) {
                    var button = jQuery(event.relatedTarget)
                    var name = button.data('name')
                    var img = button.data('img')
                    var description = button.data('description')
                    var modal = jQuery(this)
                    modal.find('.modal-body #name').val(name);
                    modal.find('.modal-body #description').val(description);
                    modal.find('.modal-body #img').attr('src','http://168.62.169.88/ShopTransom3/pub/media/catalog/product/'+img);
                });
            });
        });
    </script>
<?php endif; ?>
