
<style>
/* table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%} */

.table {
  width: 100%;
  margin-bottom: 1rem;
  background-color: transparent;
}

.table th,
.table td {
  padding: 0.75rem;
  vertical-align: top;
  border-top: 1px solid #dee2e6;
}

.table thead th {
  vertical-align: bottom;
  border-bottom: 2px solid #dee2e6;
}

.table tbody + tbody {
  border-top: 2px solid #dee2e6;
}

.table .table {
  background-color: #fff;
}

.table-sm th,
.table-sm td {
  padding: 0.3rem;
}

.table-bordered {
  border: 1px solid #dee2e6;
}

.table-bordered th,
.table-bordered td {
  border: 1px solid #dee2e6;
}

.table-bordered thead th,
.table-bordered thead td {
  border-bottom-width: 2px;
}

.table-borderless th,
.table-borderless td,
.table-borderless thead th,
.table-borderless tbody + tbody {
  border: 0;
}

.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgba(0, 0, 0, 0.05);
}

.table-hover tbody tr:hover {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-primary,
.table-primary > th,
.table-primary > td {
  background-color: #b8daff;
}

.table-hover .table-primary:hover {
  background-color: #9fcdff;
}

.table-hover .table-primary:hover > td,
.table-hover .table-primary:hover > th {
  background-color: #9fcdff;
}

.table-secondary,
.table-secondary > th,
.table-secondary > td {
  background-color: #d6d8db;
}

.table-hover .table-secondary:hover {
  background-color: #c8cbcf;
}

.table-hover .table-secondary:hover > td,
.table-hover .table-secondary:hover > th {
  background-color: #c8cbcf;
}

.table-success,
.table-success > th,
.table-success > td {
  background-color: #c3e6cb;
}

.table-hover .table-success:hover {
  background-color: #b1dfbb;
}

.table-hover .table-success:hover > td,
.table-hover .table-success:hover > th {
  background-color: #b1dfbb;
}

.table-info,
.table-info > th,
.table-info > td {
  background-color: #bee5eb;
}

.table-hover .table-info:hover {
  background-color: #abdde5;
}

.table-hover .table-info:hover > td,
.table-hover .table-info:hover > th {
  background-color: #abdde5;
}

.table-warning,
.table-warning > th,
.table-warning > td {
  background-color: #ffeeba;
}

.table-hover .table-warning:hover {
  background-color: #ffe8a1;
}

.table-hover .table-warning:hover > td,
.table-hover .table-warning:hover > th {
  background-color: #ffe8a1;
}

.table-danger,
.table-danger > th,
.table-danger > td {
  background-color: #f5c6cb;
}

.table-hover .table-danger:hover {
  background-color: #f1b0b7;
}

.table-hover .table-danger:hover > td,
.table-hover .table-danger:hover > th {
  background-color: #f1b0b7;
}

.table-light,
.table-light > th,
.table-light > td {
  background-color: #fdfdfe;
}

.table-hover .table-light:hover {
  background-color: #ececf6;
}

.table-hover .table-light:hover > td,
.table-hover .table-light:hover > th {
  background-color: #ececf6;
}

.table-dark,
.table-dark > th,
.table-dark > td {
  background-color: #c6c8ca;
}

.table-hover .table-dark:hover {
  background-color: #b9bbbe;
}

.table-hover .table-dark:hover > td,
.table-hover .table-dark:hover > th {
  background-color: #b9bbbe;
}

.table-active,
.table-active > th,
.table-active > td {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-hover .table-active:hover {
  background-color: rgba(0, 0, 0, 0.075);
}

.table-hover .table-active:hover > td,
.table-hover .table-active:hover > th {
  background-color: rgba(0, 0, 0, 0.075);
}

.table .thead-dark th {
  color: #fff;
  background-color: #212529;
  border-color: #32383e;
}

.table .thead-light th {
  color: #495057;
  background-color: #e9ecef;
  border-color: #dee2e6;
}

.table-dark {
  color: #fff;
  background-color: #212529;
}

.table-dark th,
.table-dark td,
.table-dark thead th {
  border-color: #32383e;
}

.table-dark.table-bordered {
  border: 0;
}

.table-dark.table-striped tbody tr:nth-of-type(odd) {
  background-color: rgba(255, 255, 255, 0.05);
}

.table-dark.table-hover tbody tr:hover {
  background-color: rgba(255, 255, 255, 0.075);
}

@media (max-width: 575.98px) {
  .table-responsive-sm {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    -ms-overflow-style: -ms-autohiding-scrollbar;
  }
  .table-responsive-sm > .table-bordered {
    border: 0;
  }
}

@media (max-width: 767.98px) {
  .table-responsive-md {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    -ms-overflow-style: -ms-autohiding-scrollbar;
  }
  .table-responsive-md > .table-bordered {
    border: 0;
  }
}

@media (max-width: 991.98px) {
  .table-responsive-lg {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    -ms-overflow-style: -ms-autohiding-scrollbar;
  }
  .table-responsive-lg > .table-bordered {
    border: 0;
  }
}

@media (max-width: 1199.98px) {
  .table-responsive-xl {
    display: block;
    width: 100%;
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
    -ms-overflow-style: -ms-autohiding-scrollbar;
  }
  .table-responsive-xl > .table-bordered {
    border: 0;
  }
}

.table-responsive {
  display: block;
  width: 100%;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
  -ms-overflow-style: -ms-autohiding-scrollbar;
}

.table-responsive > .table-bordered {
  border: 0;
}

</style>

<?php
$trackingHistory = $this->getShipmentHistory();
$trackingStatus = $this->getShipmentStatus();
$status = "";


if(isset($trackingHistory["error"])){
    echo "Información no disponible";
}
else {

    
switch ($trackingStatus["TrackingStatus"]) {
    case "WAITING":
        $status = "Esperando recolección";
        break;
    case "IN_TRANSIT":
        $status = "Paquete en tránsito";
        break;
    case "ON_DELIVERY":
        $status = "Paquete en proceso de entrega";
        break;
    case "DELIVERED":
        $status = "Paquete entregado";
        break;

    case "RETURNED":
        $status = "Paquete devuelto";
        break;
    
    case "CANCELLED":
        $status = "Guía cancelada o expirada";
    break;
        
    case "EXCEPTION":
        $status = "Paquetes con errores de entrega";
    break;

    default:
        echo "No disponible";
}

    ?>

<div>
          <table class="table" id="tracking-status-table">
           
            <thead class="thead-dark">
                <tr>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Servicio') ?></th>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Status') ?></th>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Tracking Number') ?></th>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Fecha estimada de llegada') ?></th>
                </tr>
            </thead>
            <tbody>
              <tr>
                  <td data-th="<?= $block->escapeHtml(__('Servicio')) ?>" ><?= /* @escapeNotVerified */ $trackingStatus["CourierName"] ?></td>
                  <td data-th="<?= $block->escapeHtml(__('Status')) ?>" ><?= /* @escapeNotVerified */  $status; ?></td>
                  <td data-th="<?= $block->escapeHtml(__('Tracking Number')) ?>" ><?= /* @escapeNotVerified */  $trackingStatus["TrackingNumber"] ?></td>
                  <td data-th="<?= $block->escapeHtml(__('Fecha estimada de llegada')) ?>" ><?= /* @escapeNotVerified */  $trackingStatus["EstimatedDeliveryDate"] ?></td>
              </tr>
            </tbody>
        </table>


        <table class="table" id="tracking-history-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Historial de envío')  ?></caption>
            <br>
            <thead class="thead-dark">
                <tr>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Details') ?></th>
                    <th scope="col" ><?= /* @escapeNotVerified */ __('Location') ?></th> 
              
                </tr>
            </thead>
            <tbody>
                <?php foreach ($trackingHistory as $values): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" ><?= /* @escapeNotVerified */ $values["Date"] ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Details')) ?>" ><?= /* @escapeNotVerified */ $values["Details"] ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Location')) ?>" ><?= /* @escapeNotVerified */ $values["Location"] ?></td>
                    </tr>
                <?php 
            //$trackingModel->getTrackingPopupUrlBySalesModel($_order)
            endforeach; ?>
            </tbody>
        </table>
</div>

    <?php
}
    ?>




